[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ev = "5V11nhm8AMcC8nn1VmyjqXvwLms5pGJVdVSco7FsahwX"

[programs.devnet]
ev = "5V11nhm8AMcC8nn1VmyjqXvwLms5pGJVdVSco7FsahwX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/pramaths/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
